### ISSUE TITLE
Issue with Gates / Doors

### ISSUE THREAD

**Issue by erox455** [shun126/UE5-DungeonGeneratorDemo#11]
Doors spawn in the middle of a room and multiple doors lead to the same hallway.
//Edit: And sometimes it creates a "DungeonWall" and a Gate or Door at the same location when using sublevels.

![Screenshot 2024-05-05 191709](https://github.com/shun126/UE5-DungeonGeneratorDemo/assets/26382304/6da7b5ec-5673-4bce-bb94-422bf1a71d15)
![Screenshot 2024-05-05 191615](https://github.com/shun126/UE5-DungeonGeneratorDemo/assets/26382304/a428e1e4-4e0e-4355-bab7-da1130432d29)
![Screenshot 2024-05-05 191536](https://github.com/shun126/UE5-DungeonGeneratorDemo/assets/26382304/d0cfc16b-0a82-41b6-93ee-c6983be7212f)

![Screenshot 2024-05-04 194709](https://github.com/shun126/UE5-DungeonGeneratorDemo/assets/26382304/2c0ccdc5-d1e7-44c0-aefc-9449d69fcaa1)
![Screenshot 2024-05-04 184054](https://github.com/shun126/UE5-DungeonGeneratorDemo/assets/26382304/e53ce680-0742-4b29-899d-0ff5bf2f704c)

**Comment by shun126** [comment]
Thank you for your report. I found the problem. I will release it after verifying the operation.

ご報告ありがとうございました。おかげで原因が分かりました。動作の検証をしてからリリースいたしますので、もうしばらくお待ちください。

**Comment by erox455** [comment]
Tested it and looks really good so far! Thank you :)
