### ISSUE TITLE
Sometimes failed to generate when i test this demo

### ISSUE THREAD

**Issue by MichaelLiew1990** [shun126/UE5-DungeonGeneratorDemo#27]
I'm using HISM method, UE5.4 latest marketplace plugin and latest demo project

DungeonGeneratorLogger: generation start: Synchronize RandomSeed x=161003d2, y=712ea3e6, z=0e8669f3, w=ae0c9685, CRC32=ffffffff, Server
DungeonGeneratorLogger: generation start:       Local RandomSeed x=6081603b, y=8795f55b, z=ea6486c7, w=5df8ab9a, CRC32=ffffffff, Server
DungeonGeneratorLogger: SeparateRooms: 0.000003 seconds
DungeonGeneratorLogger: ExpandSpace: 0.000000 seconds
DungeonGeneratorLogger: MissionGraph: Skipped
DungeonGeneratorLogger: Voxel: 経路の探索に失敗しました (15,14,2)-(15,15,3)
DungeonGeneratorLogger: Error: 生成可能な門が見つからない 5: ID=32816 (15,14,3)-(14,18,3)
DungeonGeneratorLogger: Error: OK .. 0 M: ID=32811 (16392:17.000000,15.000000,2.500000)-(16395:18.000000,15.000000,4.500000)
DungeonGeneratorLogger: Error: OK .. 1 M: ID=32812 (16393:15.000000,14.500000,5.000000)-(16392:17.000000,15.000000,2.500000)
DungeonGeneratorLogger: Error: OK .. 2 M: ID=32813 (16397:14.000000,18.000000,5.000000)-(16384:11.000000,17.000000,4.500000)
DungeonGeneratorLogger: Error: OK .. 3 M: ID=32814 (16402:10.500000,21.000000,6.500000)-(16399:7.000000,20.500000,6.000000)
DungeonGeneratorLogger: Error: OK .. 4 M: ID=32815 (16386:17.000000,20.000000,6.000000)-(16397:14.000000,18.000000,5.000000)
DungeonGeneratorLogger: Error: NG .. 5 M: ID=32816 (16397:14.000000,18.000000,5.000000)-(16393:15.000000,14.500000,5.000000)
DungeonGeneratorLogger: Error: -- .. 6 M: ID=32817 (16396:14.000000,22.500000,4.500000)-(16402:10.500000,21.000000,6.500000)
DungeonGeneratorLogger: Error: -- .. 7 M: ID=32818 (16396:14.000000,22.500000,4.500000)-(16386:17.000000,20.000000,6.000000)
DungeonGeneratorLogger: Error: -- .. 8 M: ID=32819 (16386:17.000000,20.000000,6.000000)-(16389:21.000000,19.000000,2.000000)
DungeonGeneratorLogger: Error: -- .. 9 M: ID=32820 (16390:7.000000,15.000000,6.500000)-(16384:11.000000,17.000000,4.500000)
DungeonGeneratorLogger: Error: -- .. 10 M: ID=32821 (16387:21.000000,23.500000,6.000000)-(16389:21.000000,19.000000,2.000000)
DungeonGeneratorLogger: Error: -- .. 11 M: ID=32822 (16391:7.000000,9.500000,6.000000)-(16385:11.500000,10.500000,5.000000)
DungeonGeneratorLogger: Error: -- .. 12 M: ID=32823 (16398:30.500000,12.000000,5.500000)-(16401:26.500000,14.500000,1.500000)
DungeonGeneratorLogger: Error: -- .. 13 M: ID=32824 (16399:7.000000,20.500000,6.000000)-(16403:3.500000,24.000000,5.500000)
DungeonGeneratorLogger: Error: -- .. 14 M: ID=32825 (16400:27.500000,19.500000,4.000000)-(16401:26.500000,14.500000,1.500000)
DungeonGeneratorLogger: Error: -- .. 15 M: ID=32826 (16393:15.000000,14.500000,5.000000)-(16385:11.500000,10.500000,5.000000)
DungeonGeneratorLogger: Error: -- .. 16 M: ID=32827 (16391:7.000000,9.500000,6.000000)-(16388:6.000000,3.500000,5.000000)
DungeonGeneratorLogger: Error: -- .. 17 M: ID=32828 (16389:21.000000,19.000000,2.000000)-(16400:27.500000,19.500000,4.000000)
DungeonGeneratorLogger: Error: -- .. 18 M: ID=32829 (16394:16.000000,28.500000,5.000000)-(16396:14.000000,22.500000,4.500000)
DungeonGeneratorLogger: Error: -- .. 19  : ID=32831 (16390:7.000000,15.000000,6.500000)-(16385:11.500000,10.500000,5.000000)
DungeonGeneratorLogger: Error: -- .. 20  : ID=32833 (16398:30.500000,12.000000,5.500000)-(16385:11.500000,10.500000,5.000000)
DungeonGeneratorLogger: Error: -- .. 21  : ID=32832 (16388:6.000000,3.500000,5.000000)-(16401:26.500000,14.500000,1.500000)
DungeonGeneratorLogger: Error: -- .. 22  : ID=32830 (16398:30.500000,12.000000,5.500000)-(16391:7.000000,9.500000,6.000000)
DungeonGeneratorLogger: Error: Room: ID=16388 (X=4,Y=2,Z=4) (W=4,D=3,H=2) center(6.000000, 3.500000, 5.000000)
DungeonGeneratorLogger: Error: Room: ID=16391 (X=5,Y=7,Z=5) (W=4,D=5,H=2) center(7.000000, 9.500000, 6.000000)
DungeonGeneratorLogger: Error: Room: ID=16385 (X=10,Y=9,Z=3) (W=3,D=3,H=4) center(11.500000, 10.500000, 5.000000)
DungeonGeneratorLogger: Error: Room: ID=16390 (X=6,Y=13,Z=5) (W=2,D=4,H=3) center(7.000000, 15.000000, 6.500000)
DungeonGeneratorLogger: Error: Room: ID=16384 (X=10,Y=16,Z=4) (W=2,D=2,H=1) center(11.000000, 17.000000, 4.500000)
DungeonGeneratorLogger: Error: Room: ID=16393 (X=14,Y=13,Z=3) (W=2,D=3,H=4) center(15.000000, 14.500000, 5.000000)
DungeonGeneratorLogger: Error: Room: ID=16399 (X=6,Y=18,Z=4) (W=2,D=5,H=4) center(7.000000, 20.500000, 6.000000)
DungeonGeneratorLogger: Error: Room: ID=16392 (X=15,Y=13,Z=2) (W=4,D=4,H=1) center(17.000000, 15.000000, 2.500000)
DungeonGeneratorLogger: Error: Room: ID=16397 (X=13,Y=17,Z=3) (W=2,D=2,H=4) center(14.000000, 18.000000, 5.000000)
DungeonGeneratorLogger: Error: Room: ID=16395 (X=17,Y=13,Z=3) (W=2,D=4,H=3) center(18.000000, 15.000000, 4.500000)
DungeonGeneratorLogger: Error: Room: ID=16402 (X=9,Y=18,Z=6) (W=3,D=6,H=1) center(10.500000, 21.000000, 6.500000)
DungeonGeneratorLogger: Error: Room: ID=16403 (X=2,Y=23,Z=4) (W=3,D=2,H=3) center(3.500000, 24.000000, 5.500000)
DungeonGeneratorLogger: Error: Room: ID=16396 (X=13,Y=20,Z=3) (W=2,D=5,H=3) center(14.000000, 22.500000, 4.500000)
DungeonGeneratorLogger: Error: Room: ID=16386 (X=16,Y=18,Z=5) (W=2,D=4,H=2) center(17.000000, 20.000000, 6.000000)
DungeonGeneratorLogger: Error: Room: ID=16389 (X=18,Y=18,Z=0) (W=6,D=2,H=4) center(21.000000, 19.000000, 2.000000)
DungeonGeneratorLogger: Error: Room: ID=16401 (X=25,Y=12,Z=0) (W=3,D=5,H=3) center(26.500000, 14.500000, 1.500000)
DungeonGeneratorLogger: Error: Room: ID=16387 (X=19,Y=21,Z=4) (W=4,D=5,H=4) center(21.000000, 23.500000, 6.000000)
DungeonGeneratorLogger: Error: Room: ID=16394 (X=14,Y=27,Z=4) (W=4,D=3,H=2) center(16.000000, 28.500000, 5.000000)
DungeonGeneratorLogger: Error: Room: ID=16398 (X=28,Y=9,Z=4) (W=5,D=6,H=3) center(30.500000, 12.000000, 5.500000)
DungeonGeneratorLogger: Error: Room: ID=16400 (X=25,Y=18,Z=3) (W=5,D=3,H=2) center(27.500000, 19.500000, 4.000000)
DungeonGeneratorLogger: Error: Failed to generate dungeon
DungeonGeneratorLogger: Client, Remote:(GeneratedRandomSeed=13088c35, CRC32=0) Local:(GeneratedRandomSeed=13088c35, CRC32=0)

**Comment by shun126** [comment]
Sorry for the inconvenience.
It seems that it is not possible to generate passageways.
It could be that you tried to create a passage between the rooms but there are not enough space, etc.

Perhaps changing the seed of the random number will succeed in generating it.

We will improve it ASAP.please be patient
Please wait.
