### ISSUE TITLE
bug int 1.6.1

### ISSUE THREAD

**Issue by MichaelLiew1990** [shun126/UE5-DungeonGeneratorDemo#34]
I have tested your 1.6.1 version, and found bugs:
1. DestroyDungeon will not unload sub level, you can modify your code like below:
			streamLevel->SetIsRequestingUnloadAndRemoval(true);
			//streamLevel->ClearLoadedLevel();
2. Because my game is multiplayer game, so i regenerate on server then using same seed to regenerate on client, but interior(like table) not spawn on client, table i think should not need to replicated, it should spawn by your system at same position i think

**Comment by shun126** [comment]
1. thank you for your suggestion. I will revise it immediately.

2. I am not sure about the interior replication. For example, if the interior is going to be destroyed, it would be better not to spawn at the client. What do you think?

Maybe it would be better to add an attribute to spawn at the client in the interior database, as you suggested before.

**Comment by MichaelLiew1990** [comment]
2. Yes, it is better to add an attribute.

**Comment by shun126** [comment]
In plugin version 1.6.2, I have added the ability to choose the spawning method for interior actors.
