### ISSUE TITLE
Interior spawn position error

### ISSUE THREAD

**Issue by MichaelLiew1990** [shun126/UE5-DungeonGeneratorDemo#37]
Two questions,
1. I hope you can add a function to check whether a point is inside dungeon, there is only function to check inside room now, we need also Aisle or Slope and so on.
2. Show like pic blew, my bottle position error
![111](https://github.com/user-attachments/assets/c11e24f1-1231-4d2d-b724-b8cb1638f3e2)

**Comment by shun126** [comment]
That's an amazing and cool screenshot! Is this the wall of a aisle?
I want to generate enemies and traps in the aisle, but I’m struggling with the design of the detection method.
I'm concerned about the processing load if I generate a large number of DungeonAisleSensor actors like the DungeonRoomSensor.

By the way, if the artist can control the method of selecting wall meshes, would it be possible to generate richer dungeons?
I’d like to know what the artists keep in mind when creating the modules.

**Comment by MichaelLiew1990** [comment]
No, that is room wall, not aisle wall.
Don't struggling about enemy and trap, it is very easy to finished by our developer, your plugin should focus on stability, correctness and performance of code

**Comment by shun126** [comment]
I have released plugin version 1.6.2. I have carefully checked it, but if the issue is not resolved, please contact us through this ticket.

**Comment by MichaelLiew1990** [comment]
I have updated to 1.6.2, things seems become worse......
![image](https://github.com/user-attachments/assets/fd84b271-d895-4f7d-918d-3db7d6af2f53)

**Comment by shun126** [comment]
I am truly sorry for the inconvenience.
Is the radius of the pot 20 centimeters?
Could you tell me the thickness of the wall?
If the wall is thicker than the radius of the pot, I might not be detecting the wall thickness correctly.

**Comment by shun126** [comment]
We have released version 1.6.3.
If you encounter any issues, please contact us.

Thanks to your report, I came up with a better algorithm. I hope this change will resolve your issue.
