### ISSUE TITLE
Sub level floor bug

### ISSUE THREAD

**Issue by MichaelLiew1990** [shun126/UE5-DungeonGeneratorDemo#39]
![222](https://github.com/user-attachments/assets/2bc1bf77-b866-42e5-984c-9af64c3576ef)

**Comment by shun126** [comment]
I have discovered a bug that causes the sublevel selection to occur multiple times in the same room. Thank you for always reporting these issues!

**Comment by shun126** [comment]
I have released plugin version 1.6.2. I have carefully checked it, but if the issue is not resolved, please contact us through this ticket.
