### ISSUE TITLE
Packaged game and using Steam to play across the internet.

### ISSUE THREAD

**Issue by shun126** [shun126/UE5-DungeonGeneratorDemo#54]
![image](https://github.com/user-attachments/assets/d6d555a6-4735-42e9-923e-530fac86830f)

This is what we are dealing with.

The client is the left picture and host is the right.

Packaged game using steam subsystem.

How  should we set this up so it replicated correctly?

_Originally posted by @OnceUponAMonster in https://github.com/shun126/UE5-DungeonGeneratorDemo/discussions/52#discussioncomment-10603442_

**Comment by MichaelLiew1990** [comment]
I generate at host first and then using same seed to generate at client, not using your plugin default replication solution

**Comment by MichaelLiew1990** [comment]
> > I generate at host first and then using same seed to generate at client, not using your plugin default replication solution
> 
> But wouldn't that respawn enemies and other things spawning client side?

That is your gameplay logic, I have handle all spawn by myself

**Comment by shun126** [comment]
The dungeon meshes don’t need to be synchronized, so they are spawned separately on both the server and client. Enemies, on the other hand, need to be synchronized, so they must be spawned on the server and replicated. The same applies to doors.

**Comment by shun126** [comment]
I am testing the addition of Steam matchmaking in the Demo project.

**Comment by shun126** [comment]
I tried integrating the Steam subsystem into the demo program, and I was able to package it. If I can check the error log, I might be able to consider a solution.
I will investigate again once the error log is submitted, so I will close this isssue.
